# Generated by Django 5.2.13 on 2026-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=1024)),
                ('sku', models.CharField(max_length=32)),
                ('barcode', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='usd', max_length=3)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField()),
                ('stock_quantity', models.PositiveIntegerField()),
                ('min_stock_level', models.PositiveIntegerField()),
                ('max_stock_level', models.PositiveIntegerField()),
                ('is_in_stock', models.BooleanField(default=True)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('reserved_quantity', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-updated_at'],
            },
        ),
    ]
